//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPcinema.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaHall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CinemaHall()
        {
            this.SeatsOfCinemaHall = new HashSet<Seat>();
            this.FilmSession = new HashSet<FilmSession>();
        }
    
        public int CinemaHallID { get; set; }
        public string Title { get; set; }
        public int NumberOfSeats { get; set; }
        public bool IsVIP { get; set; }
        public bool Is3D { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> SeatsOfCinemaHall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmSession> FilmSession { get; set; }
    }
}
