//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPcinema.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatTicket
    {
        public int SeatTicketID { get; set; }
        public bool Ended { get; set; }
        public int Price { get; set; }
        public bool Bought { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual FilmSession FilmSession { get; set; }
    }
}
